var flowers = [
	'Allium',
	'Anemone',
	'Artemisia',
	'Alyssum',
	'Aster',
	'Astilbe',
	'Bachelor Button',
	'Balloon Flower',
	'Bee Balm',
	'Bellflower',
	'Blanketflower',
	'Bleeding Heart',
	'Bougainvillea',
	'Broom',
	'Butterfly Weed',
	'Butterfly Bush',
	'Camellia',
	'Catmint',
	'Chrysanthemum',
	'Clematis',
	'Columbine',
	'Coneflower',
	'Coral Bells',
	'Coreopsis',
	'Cosmos',
	'Crocus',
	'Cyclamen',
	'Dahlia',
	'Day Lily',
	'Delphinium',
	'Foxglove',
	'Gas Plant',
	'Gayfeather',
	'Geranium',
	'Gladiolus',
	'Globeflower',
	'Grape Hyacinth',
	'Hardy Geranium',
	'Hollyhock',
	'Honeysuckle',
	'Hosta',
	'Hyacinth',
	'Hybrid Tea Roses',
	'Hydrangea',
	'Impatien',
	'Iris',
	'Jupiters Beard',
	'Kerria',
	'Lamium',
	'Lantana',
	'Larkspur',
	'Lavender',
	'Lilac',
	'Lily-of-the-Valley',
	'Lobelia',
	'Loosestrife',
	'Lupine',
	'Marigold',
	'Mock Orange',
	'Morning Glory',
	'Moon Flower',
	'Narcissus',
	'Nasturtium',
	'Nicotiana',
	'New Guinea impatien',
	'Oleander',
	'Pansy',
	'Passion Flower',
	'Peony',
	'Petunias',
	'Pinks',
	'Poppy',
	'Primrose',
	'Rhododendron',
	'Rose of Sharon',
	'Salvia',
	'Scabiosa',
	'Scilla',
	'Sedum',
	'Shasta Daisy',
	'Shrub Roses',
	'Silver Lace Vine',
	'Snap Dragon',
	'Snowball bush',
	'Snowdrops',
	'Sweet Pea',
	'Trumpet Vine',
	'Tulip',
	'Vinca',
	'Wisteria',
	'Yarrow'
]

labels = flowers;
labels.unshift('--select--');

module.exports['flowers'] = flowers;
module.exports['labels']  = labels;